---

- name: Modify Arista Interfaces
  hosts: arista

  tasks:
    - name: Modify Arista interface description
      eos_interface: name=Ethernet2 description="***IN USE***"
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https
    - name: Modify Arista Interface vlan id and mode
      eos_switchport: name=Ethernet2 mode=access access_vlan=467
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https