---

- name: Arista Restore Interface
  hosts: arista

  tasks:
    - name: Restore normal interface description
      eos_interface: name=Ethernet2 description=""
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: restore normal interface parameters
      eos_switchport: name=Ethernet2 mode=access access_vlan=1 trunk_allowed_vlans=1-4094
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: Remove VLANs
      eos_vlan: name={{item.name}} vlanid={{item.vlanid}} state=absent
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https
      with_items:
        - {name: SERVER, vlanid: 322}
        - {name: PHONES, vlanid: 467}
        - {name: CLIENTS, vlanid: 701}
