---
- name: Use NAPALM to get info from Arista
  hosts: arista
  tasks:
    - name: Get some info
      napalm_get_facts:
        hostname: "{{ eapi_hostname }}"
        username: "{{ eapi_username }}"
        password: "{{ eapi_password }}"
        dev_os: eos
        filter: [facts, interfaces, bgp_neighbors]
      register: result
      tags: facts

    - name: Debugging
      debug: var=result
      tags: facts
