---
- name: Changing a Juniper hostname with Ansible
  hosts: juniper
  gather_facts: false
  tasks:
    - name: Change the hostname
      junos_install_config:
        host={{ ansible_ssh_host }}
        file=set_hostname.conf
        overwrite=false
        user={{ juniper_user }}
        passwd={{ juniper_passwd }}
